overrides:
  vite: 8.0.14
shamefullyHoist: true
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
minimumReleaseAgeExclude:
  - "@iconify-json/unjs@1.2.4"
  - "@nuxt/ui@4.8.0"
  - "@nuxtjs/i18n@10.4.0"
  - vite@8.0.14
