export default defineAppConfig({
  ui: {
    colors: {
      primary: 'bego',
      neutral: 'zinc',
    },
    icons: {
      arrowUp: 'i-mingcute-arrow-up-line',
      arrowDown: 'i-mingcute-arrow-down-line',
      caution: 'i-mingcute-warning-line',
      copy: 'i-mingcute-copy-2-line',
      copyCheck: 'i-mingcute-check-2-fill',
      dark: 'i-mingcute-moon-line',
      error: 'i-mingcute-close-circle-line',
      external: 'i-mingcute-external-link-line',
      eye: 'i-mingcute-eye-2-line',
      eyeOff: 'i-mingcute-eye-close-line',
      file: 'i-mingcute-file-line',
      folder: 'i-mingcute-folder-line',
      folderOpen: 'i-mingcute-folder-open-line',
      hash: 'i-mingcute-hashtag-line',
      info: 'i-mingcute-information-line',
      light: 'i-mingcute-sun-line',
      menu: 'i-mingcute-menu-line',
      panelClose: 'i-mingcute-layout-leftbar-close-line',
      panelOpen: 'i-mingcute-layout-leftbar-open-line',
      reload: 'i-mingcute-refresh-anticlockwise-1-line',
      stop: 'i-mingcute-stop-line',
      success: 'i-mingcute-check-circle-line',
      system: 'i-mingcute-computer-line',
      tip: 'i-mingcute-light-line',
      warning: 'i-mingcute-alert-line',
      arrowLeft: 'i-mingcute-arrow-left-line',
      arrowRight: 'i-mingcute-arrow-right-line',
      check: 'i-mingcute-check-line',
      chevronDoubleLeft: 'i-mingcute-arrows-left-line',
      chevronDoubleRight: 'i-mingcute-arrows-right-line',
      chevronDown: 'i-mingcute-down-line',
      chevronLeft: 'i-mingcute-left-line',
      chevronRight: 'i-mingcute-right-line',
      chevronUp: 'i-mingcute-up-line',
      close: 'i-mingcute-close-line',
      ellipsis: 'i-mingcute-more-1-line',
      loading: 'i-mingcute-refresh-2-line',
      minus: 'i-mingcute-minimize-line',
      plus: 'i-mingcute-add-line',
      search: 'i-mingcute-search-3-line',
    },
  },
})
